apps/csua_backend/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("", include("apps.main_page.urls")),
    path("", include("apps.db_data.urls")),
    path("ldap/", include("apps.ldap.urls")),
    path("outreach/", include("apps.outreach.urls")),
    path("admin/", admin.site.urls),
    path("newuser/", include("apps.newuser.urls")),
    path("computers/", include("apps.tracker.urls")),
    path("slack/", include("apps.slackbot.urls")),
    path("discord/", include("apps.discordbot.urls")),
    path(
        "reset-password/",
        include("apps.password_reset.urls", namespace="password_reset"),
    ),
]

apps/ldap/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views
from .admin_views import admin, admin_group, admin_user, admin_validate

urlpatterns = [
    path("user/<username>/", views.user),
    path("user/<username>/groups/", views.user_groups),
    path("admin/", admin, name="ldap_admin"),
    path("admin/validate_groups/", admin_validate, name="ldap_admin_validate_groups"),
    path("admin/group/<groupname>/", admin_group, name="ldap_admin_group"),
    path("admin/user/<username>/", admin_user, name="ldap_admin_user"),
]

apps/password_reset/urls.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.urls import path

from . import views

app_name = "password_reset"

urlpatterns = [
    path("", views.RequestPasswordResetView, name="request-reset-password"),
    path("token/", views.RequestPasswordResetView, name="reset-password-token"),
    path(
        "reset-password-confirm/<uid>/<token>",
        views.PasswordResetView.as_view(),
        name="reset-password-confirm",
    ),
]

apps/password_reset/views.py
from django import forms
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import Context
from django.template.loader import render_to_string

# this is for testing purposes
from django.test import override_settings
from django.urls import reverse
from django.utils.html import strip_tags
from django.views import View
from django.views.decorators.http import require_POST

from apps.ldap.utils import change_password, get_user_email, user_exists
from apps.newuser.utils import valid_password

from .tokens import account_activation_token

REDIRECT = "/"


class RequestPasswordResetForm(forms.Form):
    username = forms.CharField(label="Username")


class PasswordResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(), label="Enter password")
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(), label="Confirm password"
    )

    def clean(self):
        form_data = super().clean()
        password = form_data.get("password")
        confirm_password = form_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords must match!")
        elif not valid_password(password):
            raise forms.ValidationError("Password must meet requirements!")

        return form_data


class PasswordResetView(View):
    def post(self, request, uid, token):
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data["password"]
            confirm_password = form.cleaned_data["confirm_password"]
            success = change_password(uid, password)
            if not success:
                raise Exception("Change password failed")
            return render(request, "password_reset/resetsuccess.html")
        else:
            context = {"form": form, "uid": uid, "token": token}
            return render(request, "password_reset/resetpasswordconfirm.html", context)

    def get(self, request, uid, token):
        print(uid, token)
        if not user_exists(uid):
            user = None
        else:
            user = uid

        # getting here just need to get back the pass
        if user is not None and account_activation_token.check_token(user, token):
            form = PasswordResetForm()
            context = {"form": form, "uid": uid, "token": token}
            return render(request, "password_reset/resetpasswordconfirm.html", context)
        else:
            print("invalid link")
            return redirect(REDIRECT)


def get_html_email(username, email, token):
    return render_to_string(
        "password_reset_email.html", {"uid": username, "email": email, "token": token}
    )


def RequestPasswordResetView(request):
    if request.method == "POST":
        form = RequestPasswordResetForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            token = account_activation_token.make_token(username)
            user_email = get_user_email(username)
            html_message = get_html_email(username, user_email, token)
            if user_email is not None:
                send_mail(
                    subject="CSUA Account Password Reset Link",
                    message=strip_tags(html_message),
                    html_message=html_message,
                    from_email="django@csua.berkeley.edu",
                    recipient_list=[user_email],
                )
                return redirect(reverse("password_reset:request-reset-password"))
            else:
                return redirect(reverse("password_reset:request-reset-password"))
        else:
            pass  # form failure
    else:
        form = RequestPasswordResetForm()

    return render(request, "password_reset/requestpasswordreset.html", {"form": form})

templates/password_reset/requestpasswordreset.html
{% extends "base.html" %}
{% block title %}Request Password Reset{% endblock %}
{% block content %}
<section class="section container">
    <div class="box content" id="top">
        <h1>Request a Password Reset</h1>

        <p>
        Whoops! It seems you forgot your password. That's okay! We can fix that. Just enter your username and we will send a link to your Berkeley email in which you can reset your password. If you made your account before we asked for your email, please contact root staff. Thank you.
    </div>
    <div class='box'>
        <form action="{% url 'password_reset:request-reset-password' %}" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
    </div>
</section>
{% endblock %}
{# vim:set et sw=4: #}

templates/password_reset/resetpasswordconfirm.html
{% extends "base.html" %}
{% block title %}Reset Your Password{% endblock %}
{% block content %}
<section class="section container">
    <div class="box content" id="top">
        <h1>Reset Your Password</h1>

        <p>
        Enter your new password here to reset your CSUA account password!
        </p>
        <div class='box'>
            <form action="{% url 'password_reset:reset-password-confirm' uid token %}" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Submit" />
            </form>
        </div>
</section>
{% endblock %}
{# vim:set et sw=4: #}

templates/password_reset/resetsuccess.html
{% extends "base.html" %}
{% block title %}Success!{% endblock %}
{% block content %}
<section class="section container">
    <div class="box content" id="top">
        <center>
        <h1>You've successfully changed your password!</h1>
        </center>
    </div>
</section>
{% endblock %}

{# vim:set et sw=4: #}