apps/csua_backend/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("", include("apps.main_page.urls")),
    path("", include("apps.db_data.urls")),
    path("ldap/", include("apps.ldap.urls")),
    path("outreach/", include("apps.outreach.urls")),
    path("admin/", admin.site.urls),
    path("newuser/", include("apps.newuser.urls")),
    path("computers/", include("apps.tracker.urls")),
    path("slack/", include("apps.slackbot.urls")),
    path("discord/", include("apps.discordbot.urls")),
    path(
        "reset-password/",
        include("apps.password_reset.urls", namespace="password_reset"),
    ),
]

apps/ldap/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views
from .admin_views import admin, admin_group, admin_user, admin_validate

urlpatterns = [
    path("user/<username>/", views.user),
    path("user/<username>/groups/", views.user_groups),
    path("admin/", admin, name="ldap_admin"),
    path("admin/validate_groups/", admin_validate, name="ldap_admin_validate_groups"),
    path("admin/group/<groupname>/", admin_group, name="ldap_admin_group"),
    path("admin/user/<username>/", admin_user, name="ldap_admin_user"),
]

apps/newuser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="newuser"),
    path("remote/", views.request_remote_newuser, name="newuser-remote-request"),
    path("remote/<email>/<token>/", views.remote_newuser, name="newuser-remote"),
]

apps/password_reset/urls.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.urls import path

from . import views

app_name = "password_reset"

urlpatterns = [
    path("", views.RequestPasswordResetView, name="request-reset-password"),
    path("token/", views.RequestPasswordResetView, name="reset-password-token"),
    path(
        "reset-password-confirm/<uid>/<token>",
        views.PasswordResetView.as_view(),
        name="reset-password-confirm",
    ),
]

apps/newuser/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.ldap.utils import user_exists

from .utils import valid_password

usernameWhitelist = set(".-_")


def validate_username_chars(value):
    if not all(c.isalnum() or c in usernameWhitelist for c in value):
        raise ValidationError(
            "Username must consist of alphanumeric characters and ., -, or _"
        )


def validate_username_not_in_use(value):
    if user_exists(value):
        raise ValidationError(f"Username {value} is taken")


class RemoteEmailRequestForm(forms.Form):
    email = forms.EmailField(label="Email")


class NewUserForm(forms.Form):
    full_name = forms.CharField(label="Full Name")
    student_id = forms.IntegerField(
        label="Student ID", min_value=100000, max_value=10000000000
    )
    email = forms.EmailField()
    username = forms.CharField(
        validators=[validate_username_chars, validate_username_not_in_use]
    )
    password = forms.CharField(widget=forms.PasswordInput())
    # enroll_jobs = forms.BooleanField(required=False, label="Jobs@ List Opt-in")
    agree_rules = forms.BooleanField(required=True)

    def clean(self):
        form_data = super().clean()
        password = form_data.get("password")
        if not valid_password(password):
            raise ValidationError("Password must meet requirements")
        return form_data


class NewUserFormOfficerVerified(NewUserForm):
    officer_username = forms.CharField(label="Officer Username")
    officer_password = forms.CharField(
        widget=forms.PasswordInput(), label="Officer Password"
    )

apps/newuser/views.py
import logging
import pathlib
import shlex
import subprocess

from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views.decorators.debug import sensitive_post_parameters, sensitive_variables

from apps.ldap.utils import create_new_user, delete_user, email_exists, validate_officer

from .forms import NewUserForm, NewUserFormOfficerVerified, RemoteEmailRequestForm
from .tokens import newuser_token_generator

usernameWhitelist = set(".-_")
emailWhitelist = set("@+").union(usernameWhitelist)
logger = logging.getLogger(__name__)

newuser_script = pathlib.Path(__file__).parent.absolute() / "config_newuser"


@sensitive_post_parameters("password", "officer_password")
def index(request):
    if request.method == "POST":
        form = NewUserFormOfficerVerified(request.POST)
        context = {"form": form, "remote": False}
        if form.is_valid():
            if validate_officer(
                form.cleaned_data["officer_username"],
                form.cleaned_data["officer_password"],
            ):
                return _make_newuser(request, form, context)
            else:
                messages.error(request, "Officer credentials are incorrect!")
        else:
            messages.error(request, "Form is invalid!")
    else:
        form = NewUserFormOfficerVerified()
        context = {"form": form, "remote": False}

    return render(request, "newuser.html", context)


@sensitive_post_parameters("password")
def remote_newuser(request, email, token):
    if newuser_token_generator.check_token(email, token):
        if request.method == "POST":
            form = NewUserForm(request.POST)
            if form.is_valid():
                form_email = form.cleaned_data["email"]
                if form_email == email:
                    return _make_newuser(
                        request,
                        form,
                        {"email": email, "form": form, "token": token, "remote": True},
                    )
                else:
                    messages.error(request, "You must use the same email, try again")
                    data = form.cleaned_data
                    data["email"] = email
                    form = NewUserForm(initial=data)
        else:
            form = NewUserForm(initial={"email": email})
        return render(
            request,
            "newuser.html",
            {"email": email, "form": form, "token": token, "remote": True},
        )
    else:
        messages.error(
            request,
            "Token is invalid! Either the token and email don't match or you've waited too long to open the link.",
        )
        return render(request, "newuser.html", {"remote": True, "form": None})


def _make_newuser(request, form, context):
    """Creates a new user in LDAP and runs config_newuser
    if config_newuser fails, the user account is deleted to prevent the user
    account from being in limbo."""
    # enroll_jobs = "true" if form.cleaned_data["enroll_jobs"] else "false"
    # disabling temporarily before the mailman3 migration
    enroll_jobs = "false"
    success, uid = create_new_user(
        form.cleaned_data["username"],
        form.cleaned_data["full_name"],
        form.cleaned_data["email"],
        form.cleaned_data["student_id"],
        form.cleaned_data["password"],
    )
    email = shlex.quote(form.cleaned_data["email"])
    username = shlex.quote(form.cleaned_data["username"])
    if success:
        config_newuser_process = subprocess.run(
            ["sudo", str(newuser_script), username, email, str(uid), enroll_jobs],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if config_newuser_process.returncode == 0:
            logger.info(f"New CSUA member! Username: {username} Email: {email}")
            return render(request, "create_success.html")
        else:
            messages.error(
                request,
                "Failed to run config_newuser. Please contact #website on slack for assistance.",
            )
            if delete_user(form.cleaned_data["username"]):
                logger.error(
                    f"Failed to run config_newuser. Username: {username} Email: {email}",
                    exc_info=None,
                    extra={"request": request},
                )
            else:
                logger.error(
                    f"Failed to run config_newuser and failed to delete user. Username: {username} Email: {email}"
                )
    else:
        if uid == -1:
            logger.error(
                f"Failed to bind as newuser. Username: {username} Email: {email}"
            )
            messages.error(
                request,
                "Internal error, failed to bind as newuser. Please report this to #website.",
            )
        else:
            messages.error(request, "Your username is already taken.")

    return render(request, "newuser.html", context)


def request_remote_newuser(request):
    """Sends an email to the user with a link to newuser-remote"""
    if request.method == "POST":
        form = RemoteEmailRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            token = newuser_token_generator.make_token(email)
            html_message = render_to_string(
                "newuser_email.html", {"email": email, "token": token}
            )
            if not email_exists(email):
                if email.endswith("@berkeley.edu"):
                    send_mail(
                        subject="CSUA New User Creation Link",
                        message=strip_tags(html_message),
                        html_message=html_message,
                        from_email="django@csua.berkeley.edu",
                        recipient_list=[email],
                    )
                    messages.info(request, "Email sent!")
                else:
                    messages.error(
                        request,
                        "Email must be @berkeley.edu. Please contact us if this is an issue.",
                    )
            else:
                messages.error(request, "Email exists in system!")
    else:
        form = RemoteEmailRequestForm()
    return render(request, "newuserremoterequest.html", {"form": form})

templates/add_officer.html
{% extends "base.html" %}
{% block title %}Create or Update Officer{% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="content box">
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li>{{ message.tags|upper }}: {{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          <h1>Create or Update Officer</h1>
          <p>Current semester: {{ semester }}</p>
          <form enctype="multipart/form-data" method="post" action="{% url 'add-officer' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update or Create</button>
          </form>
          <br>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{# vim: set et ts=2 sw=2 tw=200: #}

templates/base.html
{% load static %}
{% load db_data_tags %}
{% load markdown_deux_tags %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}DEFAULT{% endblock %} | CSUA</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/common.css" %}">
    <link rel="stylesheet" href="{% static "css/thirdparty/bulma.min.css" %}">
    <script defer src="{% static "icons.js" %}"></script>
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        // to get mobile navbar to work
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        if ($navbarBurgers.length > 0) {
          $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {
              const target = el.dataset.target;
              const $target = document.getElementById(target);
              el.classList.toggle('is-active');
              $target.classList.toggle('is-active');
            });
          });
        }
      });
    </script>
    {% block head_content %}{% endblock %}
  </head>
  <body>
    <div id="body-container">
      <nav id="navbar" class="navbar" role="navigation", aria-label="main navigation">
        <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
              <img src="{% static 'images/pic.png' %}" width="36" height="28">
            </a>
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
          <div id="navMenu" class="navbar-menu">
            <div class="navbar-start">
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="/events/">
                  <span class="icon">
                    <i class="fas fa-calendar-alt"></i>
                  </span>
                  <span>
                    Events
                  </span>
                </a>
                <div class="navbar-dropdown">
                  <a class="navbar-item" href="{% url 'workshops' %}">
                    Workshops
                  </a>
                </div>
              </div>

              <div class="navbar-item has-dropdown is-hoverable">
                <span class="navbar-link">
                  <span class="icon">
                    <i class="fa fa-users"></i>
                  </span>
                  <span>
                    About Us
                  </span>
                </span>

                <div class="navbar-dropdown">
                  <a class="navbar-item" href="{% url 'politburo' %}">
                    Politburo
                  </a>

                  <a class="navbar-item" href="{% url 'officers' %}">
                    Officers
                  </a>

                  <a class="navbar-item" href="{% url 'constitution' %}">
                    Constitution
                  </a>
                </div>
              </div>

              <div class="navbar-item has-dropdown is-hoverable">
                <span class="navbar-link">
                  <span>
                    Links
                  </span>
                </span>

                <div class="navbar-dropdown">
                  <a class="navbar-item" href="https://github.com/CSUA/csua-utils/wiki">
                    Root Staff Wiki
                  </a>
                  <a class="navbar-item" href="https://csua.github.io/documentaries/">
                    CSUA documentation
                  </a>
                </div>
              </div>

              <a class="navbar-item" href="{% url 'join' %}">
                Join
              </a>

              <a class="navbar-item" href="{% url 'tutoring' %}">
                Tutoring
              </a>

              <a class="navbar-item" href="{% url 'sponsors' %}">
                Sponsors
              </a>

              <a class="navbar-item" href="{% url 'contact' %}">
                Contact Us
              </a>
            </div>

            <div class="navbar-end">
              {% if request.user.is_authenticated %}
              <a class="navbar-item" href="{% url 'my_profile' %}">
                Welcome {{ request.user.first_name }}!
              </a>
              <a class="navbar-item" href="{% url 'logout' %}">
                Logout
              </a>
              {% if request.user.is_staff %}
              <div class="navbar-item has-dropdown is-hoverable">
                <span class="navbar-link">
                  <span>
                    KGB Links
                  </span>
                </span>

                <div class="navbar-dropdown">
                  <a class="navbar-item" href="{% url 'add-officer' %}">
                    Update or Create Officers
                  </a>
                  <a class="navbar-item" href="{% url 'admin:index' %}">
                    Django Admin
                  </a>
                  <a class="navbar-item" href="{% url 'ldap_admin' %}">
                    CSUA LDAP Admin
                  </a>
                </div>
              </div>
              {% endif %}
              {% else %}
              <a class="navbar-item" href="{% url 'password_reset:request-reset-password' %}">
                Reset Password
              </a>
              <a class="navbar-item" href="{% url 'login' %}">
                Login
              </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      {% get_current_notices as notices %}
      {% if notices %}
      <div id="notices" class="hero">
        {% for notice in notices %}
        <div class="container">
          <div class="content has-text-centered">
            {{ notice.text|markdown }}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <div id="content">
        {% block content %}{% endblock %}
      </div>

      <footer id="footer" class="footer has-text-left">
        <div class="container">
          <div class="columns">
            <div class="column">
              <div class="content">
                <a href="https://www.instagram.com/ucbcsua/">
                  <i class="fab fa-instagram"></i>
                  Instagram @ucbcsua
                </a>
                <br>
                <a href="https://www.facebook.com/csua/">
                  <i class="fab fa-facebook-square"></i>
                  Like us on Facebook!
                </a>
              </div>
            </div>
            <div class="column">
              <p>
              &copy; CSUA {% now "Y" %}
              </p>
              <p>
              <a href="{% url 'contact' %}">
                Contact Us
              </a>
              </p>
            </div>
            <div class="column">
              <p>
              Made by CSUA root staff with special help from Phillip "Edward" Nunez.
              <a href="https://github.com/CSUA/csua-backend/graphs/contributors">
                Contributors
              </a>
              </p>
              <p>
              Website feedback? Make an issue or pull request on
              <a href="https://github.com/CSUA/csua-backend">
                <i class="fab fa-github"></i>
                GitHub.
              </a>
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>
<!-- Colossians 3:23 -->
{# vim: set et ts=2 sw=2: #}

templates/base_with_hero.html
{% extends "base.html" %}

{% block content %}
{% block pre_hero%}{% endblock %}
{% block hero %}
{% include "hero_with_bg_img.html" %}
{% endblock %}

<section class="section">
  <div class="container">
    {% block page_content %}{% endblock %}
  </div>
</section>
{% endblock %}
{# vim: set et ts=2 sw=2 tw=200: #}

templates/computers.html
{% extends "base.html" %}
{% block title %}Computers{% endblock %}
{% block content %}
<div class='box content'>
  <h1>CSUA KGB Backdoor</h1>
  <table class="table">
    <th>
      Computer
    </th>
    <th>
      Status
    </th>
    <th>
      User
    </th>
    <th>
      Realname
    </th>
    <th>
      Time Spent
    </th>
    {% for computer in computers %}
    <tr bgcolor='{% if computer.user is not None %}red{% else %}lightgreen{% endif %}'>
      <td>
        <strong>{{computer.hostname}}</strong>
      </td>
      <td>
	{% if computer.user is not None %}
        Occupied
	{% else %}
        Available
        {% endif %}
      </td>
      {% if computer.user is not None %}
      <td>
        {% if computer.twitchUser != None %}
        <a href="http://twitch.tv/{{ computer.twitchUser }}" id="twitch">
          {{ computer.user.username }}
          <img src="/static/images/icons/twitch.png" width="24"></img>
        </a>
        <span id="{{user.username}}" class="twitch"></span>
        {% else %}
        {{computer.user.username}}
        {% endif %}
      </td>
      <td>
        {{computer.user.realname}}
      </td>
      <td>
        {{computer.time}}
      </td>
      {% endif %}
    </tr>
    {% endfor%}
  </table>
  <br/>
  <table class="table">
    <th>
      User
    </th>
    <th>
      Time Spent
    </th>
    {% for user in users %}
    <tr>
      <td>
        {% if user.twitch != None %}
        <a href="http://twitch.tv/{{ user.twitch }}" id="twitch">
          <strong>{{user.username}}</strong><img src="/static/images/icons/twitch.png" width="24"></img>
        </a>
        <span id="{{user.username}}" class="twitch"></span>
        {% else %}
        <strong>{{user.username}}</strong>
        {% endif %}
      </td>
      <td>
        {{user.time}}
      </td>
    </tr>
    {% endfor%}
  </table>
  {% endblock %}
</div>

templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Home{% endblock %}
{% block head_content %}
<link rel="stylesheet" href="{% static "css/index.css" %}">
{% endblock %}
{% block content %}

<section id="top" class="hero is-fullheight-with-navbar has-text-centered">
  <div class="hero-body">
    <div class="container">
      <h1 id="title" class="title">
        Welcome to the CSUA
      </h1>
      <h2 class="subtitle">
        UC Berkeley Computer Science Association
      </h2>
      <a class="smooth" href="#hello-world">Start!</a>
    </div>
  </div>
</section>


<section id="hello-world" class="section has-background-light">
  <div class="container">
    <div class="content">
      <h1>Hello World!</h1>
      <p>
      The CSUA supports the undergraduate computer science student body at
      UC Berkeley and acts as an entry point to
      <a href="{% url 'sponsors' %}">industry</a>.
      We host tech talks, hackathons, info sessions,
      <a href="{% url 'workshops' %}">workshops</a>,
      LAN parties, and the biannual
      <a href="http://ucbstartupfair.com/">Startup Fair</a>.
      </p>
      <p>
      Looking for a place to learn more about computer science and meet
      other students? Come visit us at our office (311 Soda) or come to our
      <a href="/events/">events.</a>
      </p>
    </div>
  </div>
</section>

<section id="services" class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="content">
          <h1>Our Office</h1>

          <p>
          The CSUA Office is located in 311 Soda Hall&mdash;in front of the 3rd floor
          entrance to Soda Hall.
          Inside are computers, study space, a TV, a fridge, a microwave, board games, and a library.
          Business hours are 10am-7pm, at this time no gaming is allowed in the office.
          </p>

          <p>
          Officers keep the office open and work around the clock to provide
          support and community to students.
          There is always at least one officer present if the office is unlocked.
          Come say hi!
          <a href="{% url 'officers' %}">Learn more about officers here</a>
          </p>

          <b>Address</b><br />

          Computer Science Undergraduate Association<br />
          University of California, Berkeley<br />
          311 Soda Hall<br />
          Berkeley, CA 94720-1776<br />
        </div>
      </div>
      <div class="column">
        <div class="content">
          <h2>
            Technical Services
          </h2>
          <p>
          The CSUA provides computing resources, free of charge, for all members.
          We have servers that provide webhosting, shell access, email
          forwarding, and commercial-grade machine learning.
          <a href="{% url 'computing_resources' %}">Read more here.</a>
          </p>

          <p>
          Need help with getting access to, or using our systems?
          Contact root staff (root@csua)
          </p>

          <p>
          Interested in getting more involved in technical services at CSUA?
          Want to help improve our systems?
          Consider applying for root staff.
          Contact the <a href="{% url 'politburo' %}">VP of Tech</a> to learn more.
          </p>
        </div>
      </div>
      <div class="column">
        <div class="content">
          <h2>
            Events
          </h2>
          <p>
          CSUA hosts many events throughout the semester to support the
          community.
          We host
          </p>
          <ul>
            <li>Hackathons</li>
            <li>Infosessions</li>
            <li>CS Workshops</li>
            <li>LAN Parties</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="upcoming-events" class="section has-background-light">
  <div class="container">
    <div class="content">
      <a href="{% url 'events' %}"><h1>Upcoming Events</h1></a>
      {% include "upcoming_events.html" %}
    </div>
  </div>
</section>

<section id="founded" class="section has-background-blue">
  <h2 id="headline">
    Founded in 1972, CSUA is the largest and oldest computer science club on
    campus.
  </h2>
</section>

<section id="people" class="section has-background-light">
  <div class="container">
    <div class="columns">
      <div class="column content">
        <h2>The Politburo</h2>
        <p>
        The Politburo is composed of elected officers of the CSUA.
        They run most of the club's operations.
        You can contact the Politburo at politburo@csua.berkeley.edu.
        <a href="{% url 'politburo' %}">See PB membership here.</a>
        </p>
      </div>
      <div class="column content">
        <h2 id="officers">Officers</h2>
        <p>
        Officers are people you find frequently at the office.
        They’re responsible for keeping the place open and friendly.
        Many of them are experienced with programming and can help you with your classes.
        <a href="{% url 'officers' %}">Read more here.</a>
        </p>
      </div>
      <div class="column content">
        <h2>Members</h2>
        <p>
        Becoming a CSUA member is easy.
        All you have to do is
        <a href="join">sign up for an account</a>,
        and you're done!
        An account gives you access to all of our technical resources, as well as
        membership to our mailing list and slack communities.
        </p>
      </div>
      <div class="column content">
        <h2>Alumni</h2>
        <p>
        Having been around since 1972, the CSUA has a large population of alumni.
        Our alumni work at startups, big tech companies, and regularly come back
        to us looking for new talent. CSUA occassionally invites alumni to come
        speak and hosts an annual alumni lunch in order to get students to meet
        the older generations.
        </p>
      </div>
    </div>
  </div>
</section>

<section id="department" class="section has-background-blue">
  <div class="container">
    <div class="content">
      <h1 id="the-department">The Department</h1>
    </div>
    <div class="columns">
      <div class="column content">
        <h3 id="computer-science">
          <a href="http://www.cs.berkeley.edu/">Computer Science</a>
        </h3>
        <p>
        Learn more about the Computer Science department at UC Berkeley. The
        L&amp;S CS advisors can be found
        <a href="https://eecs.berkeley.edu/resources/undergrads/cs/advising">
          here</a>.
        </p>
      </div>
      <div class="column content">
        <h3 id="electrical-engineering--computer-science">
          <a href="http://www.eecs.berkeley.edu/">
            Electrical Engineering &amp; Computer Sciences
          </a>
        </h3>
        <p>
        Learn more about the Electrical Engineering &amp; Computer Sciences
        department in UC Berkeley’s College of Engineering. The EECS advisors can be found
        <a href="https://eecs.berkeley.edu/resources/undergrads/eecs/advising">
          here</a>.
        </p>
      </div>
    </div>
    <div class="content">
      <h1 id="student-orgs">Other Clubs and Organizations</h1>
    </div>
    <div class="columns">
      <div class="column content">
        <h3 id="open-computing-facility">
          <a href="https://www.ocf.berkeley.edu/">Open Computing Facility</a>
        </h3>
        <p>
        The Open Computing Facility provides free computing services to students, faculty, and staff.
        </p>
      </div>
      <div class="column content">
        <h3 id="association-of-women-in-eecs">
          <a href="https://awe.berkeley.edu/">
            Association of Women In EE &amp; CS
          </a>
        </h3>
        <p>
        AWE is a student-run organization at UC Berkeley that supports undergraduate women interested in EE and CS.
        </p>
      </div>
    </div>
    <div class="columns">
      <div class="column content">
        <h3 id="upsilon-pi-epsilon">
          <a href="https://upe.berkeley.edu/">
            Upsilon Pi Epsilon (UPE)
          </a>
        </h3>
        <p>
        Upsilon Pi Epsilon is the first international honor society for the computing and information disciplines and is endorsed by ACM and IEEE. UPE engages students with peer advice, mock interviews, resume critiques, and more.
        </p>
      </div>
      <div class="column content">
        <h3 id="eta-kappa-nu">
          <a href="https://hkn.eecs.berkeley.edu/">Eta Kappa Nu (HKN)</a>
        </h3>
        <p>
        Eta Kappa Nu (HKN) is the national EECS honor society. The Mu Chapter of HKN is one of the most active student groups on the UC Berkeley campus, offering a variety of services to the Berkeley EECS community.
        </p>
      </div>
    </div>
    <div class="columns">
      <div class="column content">
        <h3 id="society-of-women-engineers">
          <a href="https://swe.berkeley.edu/">
            Society of Women Engineers
          </a>
        </h3>
        <p>
        Society of Women Engineers is a national nonprofit organization which strives to highlight the achievements of women as leaders and engineers.
        </p>
      </div>
      <div class="column content">
        <h3 id="csm">
          <a href="https://csmentors.berkeley.edu/#/">
            Computer Science Mentors
          </a>
        </h3>
        <p>
        CSM is a student-run organization that provides guidance and resources in a smaller classroom environment through group tutoring sessions.
        </p>
      </div>
    </div>
  </div>
</section>

<section class="section has-background-light">
  <div class="container">
    <a href="#navbar">Back to top</a>
  </div>
</section>

{% endblock %}
{# vim: set et ts=2 sw=2: #}

templates/meeting_minutes.html
{% extends "base.html" %}
{% block title %}Meeting Minutes{% endblock %}
{% block content %}
<section class="section">
    <h1>CSUA Politburo Meeting Minutes</h1>
    <div class="container has-text-centered">
        <iframe src="https://docs.google.com/document/d/e/2PACX-1vQtS-SR_bg2Ra_VrPlceHr9icG4I7_qv1lZK_hkqadp1RsC-2Jzo3QgNk8TWiiyOISfldc4WVlQwsVv/pub?embedded=true" width="800" height="1000" style="border:0" frameborder="0" scrolling="yes"></iframe>
    </div>
</section>
{% endblock %}